name: invite
on:
  schedule:
    - cron:  '14 14 * * *' # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [invite]

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Invite
        env:
          INVITER_GITHUB_API_TOKEN: ${{ secrets.INVITER_GITHUB_API_TOKEN }}
        run: |
          DEBUG=0 go run main.go -dry-run=false

