name: invite
on:
  workflow_call:
    secrets:
      INVITER_GITHUB_API_TOKEN:
        description: GitHub API token
        required: true
  repository_dispatch:
    types: [invite]
  workflow_dispatch:
  pull_request:

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.25'
      - name: Invite
        env:
          INVITER_GITHUB_API_TOKEN: ${{ secrets.INVITER_GITHUB_API_TOKEN }}
        run: |
          DEBUG=1 go run main.go -dry-run=${{ github.event_name == 'pull_request' }}

