name: invite
on:
  workflow_call:
  repository_dispatch:
    types: [invite]
  workflow_dispatch:
  pull_request:

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Invite
        env:
          INVITER_GITHUB_API_TOKEN: ${{ secrets.INVITER_GITHUB_API_TOKEN }}
        run: |
          DEBUG=1 go run main.go -dry-run=${{ github.event_name == 'pull_request' }}

