name: invite (cron)
on:
  schedule:
    - cron:  '14 14 * * *' # Runs at 14:14 UTC every day
  pull_request: # for debug
jobs:
  invite:
    uses: ./.github/workflows/invite.yml
    secrets:
      INVITER_GITHUB_API_TOKEN: ${{ secrets.INVITER_GITHUB_API_TOKEN }}
