name: invite
on:
  workflow_call:
    secrets:
      INVITER_GITHUB_API_TOKEN:
        description: GitHub API token
        required: true
  repository_dispatch:
    types: [invite]
  workflow_dispatch:
  pull_request:

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: '1.24'
      - name: Invite
        env:
          INVITER_GITHUB_API_TOKEN: ${{ secrets.INVITER_GITHUB_API_TOKEN }}
        run: |
          DEBUG=1 go run main.go -dry-run=${{ github.event_name == 'pull_request' }}

